### ISSUE TITLE
Client-side command customization

### ISSUE THREAD

**Issue by Encode42** [TeamMidnightDust/TimeChanger#2]
The ability to customize the client-side time via a command would make changing the client-time on the fly less gruesome. Users with many mods may find the very slight inconvenience of having to scroll for a second very annoying when trying to change time time frequently.

Examples: `/clienttime 0`, `/clienttime 12000`

**Comment by Motschen** [comment]
Added in v1.1.0
The command syntax is `/ctime set <time>`
