### ISSUE TITLE
[Feature Request] Weather change?

### ISSUE THREAD

**Issue by SusStew** [TeamMidnightDust/TimeChanger#4]
This probably goes against what this mod is originally intended to do, but is it possible to change the weather on the client side?

**Comment by MadCow667** [comment]
https://modrinth.com/mod/clienttime

**Comment by Motschen** [comment]
This feature is now also part of TimeChanger since the 1.19.4 version :)

**Comment by MadCow667** [comment]
Oh I see that's why its closed. I thought you had gave up on this issue.
